name: Send Gmail API Email

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'  # daily at 09:00 UTC

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Write credentials/token files from secrets
        env:
          GMAIL_CREDENTIALS_JSON: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
          GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}

      - name: Send email
        run: python script.py
