name: Send Outlook Email via Microsoft Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # every day at 09:00 UTC

jobs:
  send:
    runs-on: ubuntu-latest

    env:
      MSAL_CACHE_JSON: ${{ secrets.MSAL_CACHE_JSON }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL_ADDRESS }}
      GMAIL_CREDENTIALS_JSON: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
      #GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Write credentials from secrets
        run: |
          echo "$MSAL_CACHE_JSON" > msal_cache.json
          echo "$NEW_GMAIL_CREDENTIALS_JSON" > credentials.json
          #echo "$GMAIL_TOKEN_JSON" > token.json

      - name: Send email and process files
        run: python main.py
