name: Send Outlook Email via Microsoft Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # every day at 09:00 UTC

jobs:
  send:
    runs-on: ubuntu-latest

    env:
      MSAL_CACHE_JSON: ${{ secrets.MSAL_CACHE_JSON }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      NEW_GMAIL_CREDENTIALS_JSON: ${{ secrets.NEW_GMAIL_CREDENTIALS_JSON }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      EMAIL_BODY: ${{ secrets.EMAIL_BODY }}
      COMPOSITION_PROMPT: ${{ secrets.COMPOSITION_PROMPT }}
      SUBJECT_SUGGESTION: ${{ secrets.SUBJECT_SUGGESTION }}
      COMPOSE_REMINDER: ${{ secrets.COMPOSE_REMINDER }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Write credentials from secrets
        run: |
          echo "$MSAL_CACHE_JSON" > msal_cache.json
          echo "$NEW_GMAIL_CREDENTIALS_JSON" > credentials.json

      - name: Send email and process files
        run: python main.py
